site_name: aspen
theme: readthedocs
repo_url: https://github.com/RD-Processa/Aspen

pages:
- Introducci贸n: index.md
- Registro de aplicaciones: App_Register.md
- Asegurar una clave API: Securing_AppKey.md
- Identificaci贸n de aplicaciones: App_Setup.md
- Pasos para crear un JWT : JWT-Build.md
- Solicitar un token de autenticaci贸n: JWT-Request.md
- Generar un token de autenticaci贸n: Generate-Token.md
- Mensajes de respuesta: Responses.md